repos:
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    types: [python]
    args:
      - -S

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.243
  hooks:
    - id: ruff


